name: qikserve-container
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - checkout-network
      - monit-network
  wiremock:
    image: andersonrodriguesdev/wiremock:latest
    container_name: wiremock
    build:
      context: ./wiremock
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      WIREMOCK.SERVER.STUBS: /mappings
    networks:
      - checkout-network

  checkout-api:
    image: andersonrodriguesdev/checkout-api:latest
    container_name: checkout-api
    build:
      context: ./checkout-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      WIREMOCK.BASE-URL: http://wiremock:8081
    depends_on:
      - wiremock
      - zipkin
    networks:
      - checkout-network
      - monit-network

networks:
  monit-network:
  checkout-network:
    driver: bridge