services:
  wiremock:
    image: andersonrodriguesdev/wiremock
    container_name: wiremock
    build:
      context: ./wiremock
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./wiremock:/home/wiremock:rw
      - ./wiremock/mappings:/mappings:rw
    entrypoint: ["java", "-jar", "/app.jar", "--port", "8081", "--bind-address", "0.0.0.0"]
    environment:
      WIREMOCK.SERVER.FILES: /home/wiremock/__files
      WIREMOCK.SERVER.STUBS: /home/wiremock/mappings
    networks:
      - checkout-network
  checkout-api:
    image: andersonrodriguesdev/checkout-api
    build:
      context: ./checkout-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      WIREMOCK.BASE-URL: http://wiremock:8081
    depends_on:
      - wiremock
    networks:
      - checkout-network
networks:
  checkout-network:
    driver: bridge
