services:
  wiremock:
    image: andersonrodriguesdev/wiremock:latest
    container_name: wiremock
    build:
      context: ./wiremock
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      WIREMOCK.SERVER.FILES: /__files
      WIREMOCK.SERVER.STUBS: /mappings
    networks:
      - checkout-network
  checkout-api:
    image: andersonrodriguesdev/checkout-api:latest
    build:
      context: ./checkout-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      WIREMOCK.BASE-URL: http://wiremock:8081
    depends_on:
      - wiremock
    networks:
      - checkout-network
networks:
  checkout-network:
    driver: bridge
